apiVersion: v2
kind: Deployment
metadata:
  name: ui-deployment
  namespace: ui-namespace
  labels:
    app: tracker
    component: ui
    type: deploy
    tier: frontend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector: # selects pods with labels: microservice=ui, type=pods, tier=frontend
    matchLabels:
      microservice: ui
      type: pods
      tier: frontend
  template:
    metadata:
      labels:
        microservice: ui
        type: pods
        tier: frontend
    spec:
      serviceAccountName: ui
      containers: 
        - name: ui
          image: 403188442647.dkr.ecr.us-east-2.amazonaws.com/ui-store
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: # define the configmap data as container env variables and The key from the ConfigMap becomes the environment variable name in the Pod
                name: ui-configMap
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 128m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory    