apiVersion: apps/v1
kind: Deployment

metadata: 
  name: trackr-app-deployment
  namespace: trackr-namespace
  labels:
    app: eks-trackr-app

spec:
  replicas: 2 # deploys 2 replicas (individual Pods) of docker image to cluster
  selector:
    matchLabels: 
      app: eks-trackr-app

  template: 
    metadata: 
      labels: 
        app: eks-trackr-app
    spec:
      containers:
      - name: trackr-app
        image: 403188442647.dkr.ecr.us-east-2.amazonaws.com/trackr-eks, # fetch docker image from the ECR repo
        ports: 
        - name: http
          containerPort: 8000
        imagePullPolicy: Always

    strategy:
      type: RollingUpdate
      rollingUpdate: # check this
        maxSurge: 1
        maxUnavailable: 1