apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: trackr-namespace
  labels:
    app: eks-catalog-store
    tier: backend
spec:
  selector:
    app: eks-catalog-store
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
