apiVersion: apps/v1
kind: Deployment

metadata:
  name: eks-carts-store
  namespace: carts-namespace
  labels:
    app: eks-carts-store

spec:
  replicas: 2 # number of pods
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: eks-carts-store
  template:
    metadata:
      labels:
        app: eks-carts-store
    spec:
      container:
        - name: carts-store
          image: 403188442647.dkr.ecr.us-east-2.amazonaws.com/carts-store
          ports:
            - name: http
              containerPort: 8000
