apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-deployment
  namespace: trackr-namespace
  labels:
    app: carts-store
    component: carts
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: carts-store
      tier: backend
  template:
    metadata:
      labels:
        app: carts-store
        tier: backend
    spec:
      containers:
        - name: carts-store
          image: 403188442647.dkr.ecr.us-east-2.amazonaws.com/carts-store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
