apiVersion: v1
kind: Service
metadata:
  name: carts-service
  namespace: trackr-namespace
  labels:
    app: carts-store
    component: carts
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: carts-store
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
