apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http


# the Service named "catalog-service" routes traffic to Pods that have the labels app=eks-catalog-store and tier=backend
# the DNS name is "catalog-service" aka value in the "name" field


# COMMANDS
