apiVersion: v1
kind: Service
metadata:
  name: hostname-service
  namespace: trackr-namespace
spec:
  type: NodePort
  selector:
    app: echo-hostname
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30163
