apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: tracker-catalog
    type: service
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    name: catalog
    type: pods
    component: service

# What this service does:
  # 1. Selects catalog Pods using labels that match the Pod labels in the Deployment file
  # 2. exposes itself on port 80
  # 3. targets the http port exposed by the Deployment which translates to port 8001 
