apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: trackr-namespace
  labels:
    app: eks-ui-store
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: eks-ui-store
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
