on:
    push:
        branches: [${{secrets.NEW_ECR_BRANCH}}]
env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    AWS_ACC_ID: ${{ secrets.AWS_ACC_ID }}

jobs:
    create_ecr_repo:
        runs-on: ubuntu-latest
        name: New ECR Repo
        steps: 
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              run: |
                bash ../../eks-shell/aws-credentials.sh
